### ISSUE TITLE
discourse: issue processing zcash forum

### ISSUE THREAD

**Issue by s-ben** [sourcecred/sourcecred#1440]
I tried running the discourse plugin on the [zcash forum](https://forum.zcashcommunity.com/),

`node bin/sourcecred.js discourse https://forum.zcashcommunity.com`

Got this error: 

```FetchError: request to https://forum.zcashcommunity.com/t/25608.json failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/sben/Documents/coins/sourcecred/sourcecred/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```
Tried again later (just running the command again, not deleting data) and got some warnings along with this error:

```
Warning: Encountered error 'FOREIGN KEY constraint failed' on a like by t2yax on post id 29446.
Warning: Encountered error 'FOREIGN KEY constraint failed' on a like by t2yax on post id 25320.
Warning: Encountered error 'FOREIGN KEY constraint failed' on a like by t2yax on post id 22304.
Warning: Encountered error 'FOREIGN KEY constraint failed' on a like by t2yax on post id 22367.
Warning: Encountered error 'FOREIGN KEY constraint failed' on a like by t2yax on post id 20368.
Error: 404 Not Found on: https://forum.zcashcommunity.com/user_actions.json?username=kernelpanik23&filter=1&offset=0; maybe bad serverUrl?
    at failIfMissing (webpack:///./src/plugins/discourse/fetch.js?:35:433)
    at Fetcher.likesByUser (webpack:///./src/plugins/discourse/fetch.js?:35:246)
```

Note: the forum is a few years old and quite large. May take a couple hours to run.

**Comment by decentralion** [comment]
https://github.com/sourcecred/sourcecred/pull/1443 should fix the second issue.
For the first one, we should add retry logic around the fetch to save the user from needing to re-launch themselves.

**Comment by Beanow** [comment]
The 404 seems to indicate the user not existing (anymore?), rather than there being no likes.|
As https://forum.zcashcommunity.com/u/kernelpanik23/summary is also a 404.
I wonder if the actual likes of these users are removed from the post and decremented the counter.
