### ISSUE TITLE
Bad failure message when retrieving graph with an invalid GitHub token

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#223]
Consider the command 
`node bin/sourcecred.js sourcecred sourcecred github-token=BAD`

Expected:
It will give a helpful error message stating that the github token was bad.

Actual: 
```
    /home/dandelion/git/sourcecred/bin/commands/combine.js:116
    process.on("unhandledRejection",err=>{throw err;});class CombineCommand extends __WEBPACK_IMPORTED_MODULE_0__oclif_command__["Command"]{// We disable strict-mode so that we can accept a variable number of
                                          ^
    
    TypeError: Cannot read property 'repository' of undefined
        at continuationsFromQuery (/home/dandelion/git/sourcecred/bin/commands/plugin-graph.js:437:86)
        at postQueryExhaustive (/home/dandelion/git/sourcecred/bin/commands/plugin-graph.js:468:168)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by decentralion** [comment]
Clarification: It does give a helpful warning if the token is something totally unreasonable (like `FOO`), but gives the bad failure if the token superficially looks valid.
