### ISSUE TITLE
Create a NetworkReadOnlyInstance

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#2874]
Currently, we have an awesome LocalInstance implementation that allows easy reading/writing of files from local disk. However, many use cases, such as observable notebooks and discord bots, require a Network solution. This issue is to create an implementation of the ReadOnlyInstance interface that uses a NetworkStorage object to fetch files from a URL, and add it to the API.

**Comment by blueridger** [comment]
https://github.com/sourcecred/sourcecred/tree/network-instance

I tried but it is giving me `TypeError: Only absolute URLs are supported` even though I console logged `normalize(pathJoin(this._base, resource))` and it showed `https:/raw.githubusercontent.com/1Hive/pollen/gh-pages/output/credGraph.json.gzip`

```
yarn build
node
sc = require("./dist/server/api.js")
i = new sc.sourcecred.instance.NetworkReadInstance("https://raw.githubusercontent.com/1Hive/pollen/gh-pages")
i.readCredGraph()
```

**Comment by blueridger** [comment]
The https:// prefix is not supported by normalize currently. Pushed a workaround. Now getting this error:

```
> i.readCredGraph()
https://raw.githubusercontent.com/1Hive/pollen/gh-pages/output/credGraph.json.gzip
Promise { <pending> }
> i.readCredGraph()(node:63578) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token x in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/thena/workspace/sourcecred/dist/server/api.js:9:180813
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async NetworkReadInstance.readCredGraph (/Users/thena/workspace/sourcecred/dist/server/api.js:9:180735)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:63578) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:63578) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by blueridger** [comment]
https://github.com/sourcecred/sourcecred/tree/network-instance now contains a working solution. I manually tested serving a local instance with it, as well as called the library with node. It just needs the unit/lint tests fixed.
